### ISSUE TITLE
Shorter name for yac_symbol()

### ISSUE THREAD

**Issue by mikldk** [mikldk/ryacas#34]
Shorter name for `yac_symbol()` as initially discussed in #33. Moving discussion to here.

I will not use `Sym()`, and since `sym()` is already used by `rlang` I see these options:
* `ys()` (for yacas symbol) -- I prefer this
* `ysym()` (same as above)
* `sy()` (for symbol in yacas)

Any inputs on these names or suggestions for others?

**Comment by grzegorzmazur** [comment]
Hi,
Not really speaking R I can only guess that you don't like Sym() because it goes against the lowercase naming convention?

Anyway, I don't like sy(), it's too cryptic. With respect to ys() vs ysym() I'm crossed - the former would be most likely preferred by those who already know what it means and the latter is more readable for beginners. 

Cheers,
Grzesiek

**Comment by mikldk** [comment]
Thanks for the input. I lean towards `ysym()` for readability.

**Comment by mikldk** [comment]
I have settled for `ysym()` after discussions with @hojsgaard .
