### ISSUE TITLE
Implement WithValue

### ISSUE THREAD

**Issue by mikldk** [mikldk/ryacas#43]
See <https://yacas.readthedocs.io/en/latest/reference_manual/controlflow.html#WithValue>.

**Comment by grzegorzmazur** [comment]
Hi,

I'm not completely convinced that assume is the best name for this functionality. The reason is that the term assume usually denotes more general situation, where you say that certain variables belong to specific sets. Eg you can get real or complex roots of polynomial, or you may be interested in only positive rational solutions. This mechanism is implemented eg in mathematica or sage. It's not (yet 🙂) available in yacas, but I'm not loosing my hope. Of course your approach isn't wrong, it's just assuming that a variable belongs to a one-element set. But it may cause troubles if/when more general assumptions mechanism lands in yacas.

Cheers,
Grzesiek

**Comment by mikldk** [comment]
You are of course right! I will change the name. Thank you very much for the feed-back!
